name: reviewdog
on: [pull_request]
jobs:
  markdownlint:
    name: runner / markdownlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: markdownlint
        uses: reviewdog/action-markdownlint@v0.9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
# - name: markdownlint-cli
#         uses: nosborn/github-action-markdown-cli@v3.0.1
#         with:
#           files: .
#           config_file: .markdownlint.yaml
#           ignore_files: examples/ignore/*
#           ignore_path: examples/.markdownlintignore
#           rules: examples/rules/custom.js
